from __future__ import annotations

import json
import re
from typing import Any


def _extract_enquiry(user_message: str) -> str:
    m = re.search(
        r"---BEGIN ENQUIRY---\s*(.*?)\s*---END ENQUIRY---",
        user_message,
        flags=re.DOTALL | re.IGNORECASE,
    )
    return (m.group(1) if m else user_message or "").strip()


def _classify_heuristic(text: str) -> dict[str, Any]:
    t = text.lower()
    if not t:
        return {
            "classification": "unclear",
            "confidence": 0.15,
            "confidence_rationale": "No usable text after stripping (mock).",
            "client_intent_summary": "The enquiry text was empty.",
            "suggested_staff_reply": (
                "Thank you for contacting Strata Management Consultants. "
                "We did not receive a clear message. Please reply with your scheme name, "
                "lot number, and a short description of what you need help with."
            ),
            "recommended_actions": ["Wait for a clearer message from the client"],
            "urgency": "low",
            "flags": [],
        }
    if any(
        w in t
        for w in (
            "complaint",
            "not happy",
            "unhappy",
            "frustrated",
            "disappointed",
            "unacceptable",
        )
    ):
        cls, conf = "complaint", 0.78
        rationale = "Language signals dissatisfaction or dispute (mock heuristic)."
        summary = "The owner or committee member appears to be raising a grievance or service concern."
        urgency = "high" if any(x in t for x in ("safety", "urgent", "emergency", "days", "weeks")) else "medium"
    elif any(
        w in t
        for w in ("quote", "proposal", "new scheme", "take over", "strata manager", "looking for a manager")
    ):
        cls, conf = "new_client", 0.72
        rationale = "Wording suggests onboarding or procurement of management services (mock heuristic)."
        summary = "Likely a new business or committee enquiry about strata management services."
        urgency = "medium"
    elif "?" in t and len(t) < 280 and not any(
        w in t for w in ("levy", "by-law", "committee", "agm", "maintenance", "repair")
    ):
        cls, conf = "general_question", 0.68
        rationale = "Short informational tone without a clear service or complaint thread (mock heuristic)."
        summary = "Appears to be a general information question rather than a case-specific request."
        urgency = "low"
    else:
        cls, conf = "support_request", 0.74
        rationale = "Default mock path: treated as an operational request from an existing stakeholder."
        summary = "Typical owner or committee enquiry about levies, maintenance, meetings, or records."
        urgency = "high" if any(x in t for x in ("safety", "stuck", "flood", "fire", "asap")) else "medium"

    flags: list[str] = []
    if "tribunal" in t or "ncat" in t or "court" in t:
        flags.append("mentions_legal_or_tribunal")
    if "safety" in t or "injury" in t:
        flags.append("possible_safety_issue")

    reply = (
        f"Dear owner / committee member,\n\n"
        f"Thank you for your email regarding your enquiry. We have logged this as a **{cls.replace('_', ' ')}** "
        f"and a team member will respond shortly.\n\n"
        f"If your matter is urgent, please call our office and quote your scheme address.\n\n"
        f"Kind regards,\nStrata Management Consultants\n\n"
        f"_(This draft was generated by **mock mode** — replace with a real model response in production.)_"
    )
    actions = [
        "Assign to the relevant portfolio manager based on scheme",
        "Confirm scheme name and lot number in the CRM",
    ]
    if cls == "complaint":
        actions.insert(0, "Acknowledge within business SLA; document timeline")
    if cls == "new_client":
        actions = [
            "Send capability statement and fee proposal template",
            "Schedule discovery call with committee chair",
        ]

    return {
        "classification": cls,
        "confidence": conf,
        "confidence_rationale": rationale,
        "client_intent_summary": summary,
        "suggested_staff_reply": reply,
        "recommended_actions": actions,
        "urgency": urgency,
        "flags": flags,
    }


class MockLLMClient:
    def complete_json(self, *, system: str, user: str) -> str:
        enquiry = _extract_enquiry(user)
        payload = _classify_heuristic(enquiry)
        return json.dumps(payload, ensure_ascii=False)
